# Generated by Django 5.1.7 on 2025-03-13 16:30

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=80)),
                ('street', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('neighborhood', models.CharField(max_length=80)),
                ('complement', models.CharField(blank=True, max_length=80, null=True)),
                ('cep', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_vacancies', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('class_code', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=40)),
                ('status', models.BooleanField()),
            ],
            options={
                'db_table': 'disciplines',
            },
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField()),
                ('desc', models.CharField(max_length=300)),
                ('document', models.BinaryField(blank=True, null=True)),
                ('approval_status', models.CharField(max_length=40)),
                ('observation', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'justifications',
            },
        ),
        migrations.CreateModel(
            name='Auth_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=80)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('registration_date', models.DateField()),
                ('position', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('address_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_site.address')),
            ],
            options={
                'db_table': 'auth_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=400)),
                ('release_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_site.discipline')),
            ],
            options={
                'db_table': 'classes_diaries',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('rg', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('registration_date', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_site.address')),
                ('class_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_site.class')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_date', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_site.discipline')),
                ('justification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_site.justification')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_site.student')),
            ],
            options={
                'db_table': 'absences',
            },
        ),
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
                ('final_note', models.FloatField()),
                ('frequency', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_site.discipline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_site.student')),
            ],
            options={
                'db_table': 'students_disciplines',
                'unique_together': {('student', 'discipline')},
            },
        ),
        migrations.CreateModel(
            name='User_Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=40)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_site.discipline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_disciplines',
                'unique_together': {('user', 'discipline')},
            },
        ),
    ]
