# Generated by Django 5.1.7 on 2025-03-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth_user',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='auth_user',
            name='status',
        ),
        migrations.AlterField(
            model_name='auth_user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='auth_user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
