# Generated by Django 5.1.7 on 2025-03-13 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0002_remove_auth_user_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user',
            name='address_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_site.address'),
        ),
    ]
