# Generated by Django 5.1.7 on 2025-03-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0003_alter_auth_user_address_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='auth_user',
            name='position',
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_date',
            field=models.DateTimeField(),
        ),
    ]
