# Generated by Django 5.1.7 on 2025-03-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0004_rename_full_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_user',
            old_name='address_key',
            new_name='address_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_key',
            new_name='class_id',
        ),
    ]
