# Generated by Django 5.1.7 on 2025-03-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0005_rename_address_key_auth_user_address_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auth_user',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_id',
            new_name='student_class',
        ),
    ]
