# Generated by Django 5.1.7 on 2025-03-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0006_rename_address_id_auth_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user',
            name='first_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='auth_user',
            name='last_name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
