# Generated by Django 5.1.7 on 2025-03-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0007_alter_auth_user_first_name_alter_auth_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
