# Generated by Django 5.1.7 on 2025-03-18 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0008_alter_auth_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth_user',
            name='password',
        ),
    ]
