# Generated by Django 5.1.7 on 2025-03-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0009_remove_auth_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='auth_user',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='auth_user',
            name='profession',
            field=models.CharField(default='Teacher', max_length=50),
        ),
        migrations.AddField(
            model_name='auth_user',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
