# Generated by Django 5.1.7 on 2025-03-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0010_auth_user_date_of_birth_auth_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth_user',
            name='password',
        ),
    ]
