# Generated by Django 5.1.7 on 2025-03-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0011_remove_auth_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_user',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
    ]
