# Generated by Django 5.1.7 on 2025-04-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0013_alter_auth_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='status',
        ),
        migrations.AddField(
            model_name='absence',
            name='absence_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='absence',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
