# Generated by Django 5.1.7 on 2025-04-23 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0014_remove_absence_status_absence_absence_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_site.class')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_site.discipline')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees_classes',
                'unique_together': {('employee_id', 'class_id')},
            },
        ),
        migrations.AddField(
            model_name='classdiary',
            name='employee_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_site.employeeclasses'),
        ),
    ]
