# Generated by Django 5.1.7 on 2025-04-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0015_employeeclasses_classdiary_employee_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeclasses',
            name='discipline',
        ),
    ]
