# Generated by Django 5.1.7 on 2025-04-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0016_remove_employeeclasses_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdiary',
            name='user',
        ),
    ]
