# Generated by Django 5.1.7 on 2025-04-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0017_remove_classdiary_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeClasses',
            new_name='EmployeeClass',
        ),
    ]
