# Generated by Django 5.1.7 on 2025-04-23 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0018_rename_employeeclasses_employeeclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdiary',
            old_name='employee_class',
            new_name='user_class',
        ),
        migrations.RenameField(
            model_name='employeeclass',
            old_name='employee_id',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='employeeclass',
            unique_together={('user_id', 'class_id')},
        ),
    ]
