# Generated by Django 5.1.7 on 2025-04-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0019_rename_employee_class_classdiary_user_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeclass',
            old_name='class_id',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='employeeclass',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='employeeclass',
            unique_together={('user', 'classe')},
        ),
    ]
