# Generated by Django 5.1.7 on 2025-04-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0020_rename_class_id_employeeclass_classe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdiary',
            old_name='user_class',
            new_name='employee_class',
        ),
        migrations.RenameField(
            model_name='employeeclass',
            old_name='classe',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='employeeclass',
            old_name='user',
            new_name='employee_id',
        ),
        migrations.AlterUniqueTogether(
            name='employeeclass',
            unique_together={('employee_id', 'class_id')},
        ),
    ]
