# Generated by Django 5.1.7 on 2025-04-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0021_rename_user_class_classdiary_employee_class_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeclass',
            old_name='class_id',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='employeeclass',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.AlterUniqueTogether(
            name='employeeclass',
            unique_together={('employee', 'classe')},
        ),
    ]
